### PR TITLE
upgraded egui to 0.20

### PR DESCRIPTION
**Pull request by DoeringChristian**

### CODE REVIEW

**Review by attackgoat — CHANGES_REQUESTED** [review]
The new version adds a result to `on_event` which I think in this case we could ignore, but it throws a warning about it.

Does this look good for line 200:

```rust
#[allow(unused_must_use)]
{
    self.egui_winit.on_event(&self.ctx, event);
}
```

**Comment by DoeringChristian** [comment]
I agree. Seems that the response can be ignored.

**Review by attackgoat — APPROVED** [review]

**Comment by attackgoat** [comment]
I should probably start to publish some of these `/contrib` crates, the main crate is becoming more and more production ready.

Sometime this summer I hope to get to a stable point where everything mostly works and the API is mostly ready for 1.0; although I don't think I'll bump to that version for a while just in case. I'm working on an example game that loads assets, has raster and ReSTIR ray traced GI modes, transitions between screens, menu UI, sound, etc. Once complete that would be a good indicator things are working.

**Comment by DoeringChristian** [comment]
Sounds good I hope your project gets a bit more attention once it reaches Version 1. I think it's one of the best abstractions over Vulkan for Rust.

**Comment by DoeringChristian** [comment]
As a side note I also tried to integrate screen-13 into bevy but ran into some problems. As bevy is the most popular engines in rust but uses wgpu, which does not support ray tracing, this might also be an interesting long term goal.

**Pull request merged**
